# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf2d2051ad53fd67e426320a61ca3c9f900a87e99083b4f091c1289f7b3c17d0a4ce11fbd92a78f24d7db74f752a50823a41d918f8c8ecfd4e6c7907291bf4a3

test:
  secret_key_base: 9e33f4d943ac2fecb17535ec0144dce8bf484cbc7d369439f534308e45e03f9f04d6d67705c4e8aba9d4e5f5a015fae42aac2448834e938b37b697f7f59d1332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
